### ISSUE TITLE
Erro ao verificar a energia gerada

### ISSUE THREAD

**Issue by dfares1987** [mastria/intelbras-solar#2]
bom dia para qualquer comando dado esta obtendo o erro "Erro ao verificar a energia gerada" aparentemente nao esta fazendo nem  o login na conta intelbras existe algum manual para para api dessa plataforma para que possa ajudar a fazer as correçoes?

**Comment by mastria** [comment]
me chama no email, tento te ajudar [guilherme@mastria.dev.br](mailto:guilherme@mastria.dev.br)
